### ISSUE TITLE
Fix build operation trace so that it doesn't generate deprecation warnings

### ISSUE THREAD

**Issue by ghale** [gradle/gradle-native#858] opened 2018-09-21 16:08 UTC
The build operation trace integration tests throw deprecation warnings because they try to resolve configurations without holding the project lock.

See https://github.com/gradle/gradle/pull/6475/commits/7924e437fbdd3089275c12918384abef4ba50e09

**Comment by lacasseio** [comment] 2018-10-09 17:55
After much debugging, I don't know if it's an actual issue with the Gradle code or an issue with the test code. In short, the test code listens to build operations. For each notification, [all method of the public interface are invoked](https://github.com/gradle/gradle/blob/master/subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/BuildOperationNotificationsFixture.groovy#L93-L95). The `ResolveConfigurationDependenciesBuildOperationType.Result#getRootComponent()` method [ends up been called](https://github.com/gradle/gradle/blob/master/subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/configurations/ResolveConfigurationResolutionBuildOperationResult.java#L43-L52). Then the [`ResolutionResult#getRoot()` method](https://github.com/gradle/gradle/blob/master/subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/configurations/DefaultConfiguration.java#L1381-L1384) gets called which trickles down to [`DefaultConfiguration#assertResolvingAllowed()` method](https://github.com/gradle/gradle/blob/master/subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/configurations/DefaultConfiguration.java#L1128-L1140).

My questions are:
- Should the `BuildOperationNotificationListener` be responsible of taking the mutation lock before calling the public APIs on the result? 

Or
- Should the result be aware of the project it's coming from and take the mutation lock before resolving  whatever result it needs to do?

Or
- Should the resolution happens before returning the build operation result?

**Comment by big-guy** [comment] 2018-10-09 19:59
I reverted https://github.com/gradle/gradle/commit/7924e437fbdd3089275c12918384abef4ba50e09 and ran the `BuildInitializationBuildOperationsIntegrationTest` tests.

I think the deprecation looks like it's coming from a reasonable place, so we shouldn't just fix the test code.  I think this mimics what the build scan plugin is doing and we should be able to get the right locks. The lock should be acquired much higher up in the chain (`BuildOperationCrossProjectConfigurator`?).  We shouldn't be putting locks around `ResolveConfigurationDependenciesBuildOperationType.Result` or `ResolutionResult` or anything like that.

I think this is similar to the deprecation warnings we're getting out of Play projects, but just a little earlier (during project configuration instead of DAG building).

@ghale there's a TODO here: https://github.com/gradle/gradle/blob/29bb493cbbbb2592e873caf005403f448411a0cd/subprojects/core/src/main/java/org/gradle/api/internal/project/BuildOperationCrossProjectConfigurator.java#L59

I think having the project state lock here would fix the underlying issue, but I think we could also just rely on the "lenient" lock too in the short term.  Gut feeling on what needs to be fixed to remove that TODO?

**Comment by lacasseio** [comment] 2018-10-09 20:04
[I did fix that](https://github.com/gradle/gradle/pull/7299), still need some adjustment, but it doesn't fix it as the build operation notification are coming back from nested project inside the root project. It's actually the `ResolutionResult` that contains the cross-project and that is mutating it. I will look at it more tomorrow.

**Comment by big-guy** [comment] 2018-10-10 04:10
@lacasseio this commit seems to fix things without having to fix the TODO: 
https://github.com/gradle/gradle/commit/474cb2ea5a330f070a07ca74e6f07f51400a7db9

The build operation should only deal in `ResolutionResult`, which should be effectively immutable.  Once we've resolved the configuration and generated the build operation, we have the `ResolutionResult` in the cache, so we shouldn't need to recreate it.  That eliminates the "re-resolve" part that was happening in the build operation.

The change seems to have issues, but it's not immediately obvious to me what's going on:
https://builds.gradle.org/viewQueued.html?itemId=16488839

Since you're in the same time zone, it might be worth bouncing some ideas off the dependency management folk.

**Comment by lacasseio** [comment] 2018-10-10 18:45
A fix was pushed to the branch and a new PR was open for this branch without fixing the TODO (it can be fixed as part of another issue and PR): https://github.com/gradle/gradle/pull/7330

**Comment by big-guy** [comment] 2018-10-10 20:56
@lacasseio let's wait for a response on the two questions, but otherwise LGTM

**Comment by big-guy** [comment] 2018-10-11 20:01
Cedric said he'd look at this tomorrow. It looks like this has introduced another performance regression, could you take a look and see if there's something we can do? Please pull in a dependency management person if it's related to the serializer.

**Closed** 2018-10-12 21:19 UTC
