### ISSUE TITLE
Support for XCTest testing framework in Swift

### ISSUE THREAD

**Issue by lacasseio** [gradle/gradle-native#200] opened 2017-10-04 18:39 UTC
XCTest testing framework is the most popular framework for Swift.

### Expected Behavior
XCTest is supported by Gradle for both macOS (Xcode and Corelibs runtime) and Linux (Corelibs runtime).

**Comment by eljobe** [comment] 2017-11-01 21:04
This is a duplicate of one from the other board.

**Closed by eljobe** 2017-11-01 21:04 UTC
Labels: a:roadmap, Epic, in:testing
