### ISSUE TITLE
Better handle the case where multiple plugins are applied to the same project

### ISSUE THREAD

**Issue by adammurdoch** [gradle/gradle-native#18] opened 2017-06-24 18:24 UTC
@adammurdoch commented on [Mon Jun 05 2017](https://github.com/gradle/stable-native/issues/32)

For example, when using the C++ executable and library plugins together, or one of these plugins with the Java plugins, or with the Swift plugins.

For this story, "better handle" could simply mean a better error message, or it might mean that you can build multiple components of these various types, or joint compilation or something else.

**Comment by lacasseio** [comment] 2019-03-04 22:55
Duplicate of https://github.com/gradle/gradle-native/issues/216. We will solve this using a better error message to start with.

**Closed by lacasseio** 2019-03-04 22:55 UTC
