### ISSUE TITLE
Reduce variation when there is only one variant dimension of os/architecture

### ISSUE THREAD

**Issue by ghale** [gradle/gradle-native#921] opened 2018-11-02 19:19 UTC
Currently, if we specify multiple target platforms, we include all dimensions in the variant naming, even if a variant only has one value.  For instance, if we specified linux x86 and linux x86_64, the variant naming would include "linux" even though that's the only operating system being built.

We should look at:
- task names
- output file locations
- published module names (maybe)
- configuration names

Also, tackle [this issue](https://github.com/gradle/gradle/pull/7545#discussion_r229182900) as part of this work.

**Comment by lacasseio** [comment] 2018-11-05 07:11
This issue may be a duplicate of https://github.com/gradle/gradle-native/issues/539

**Comment by big-guy** [comment] 2018-12-03 16:01
covered by other issues

**Closed by big-guy** 2018-12-03 16:01 UTC
