### ISSUE TITLE
Build logic can declare which operating systems to produce the binaries for a Swift component for

### ISSUE THREAD

**Issue by adammurdoch** [gradle/gradle-native#358] opened 2017-12-21 03:59 UTC
Allow the target operating system or systems for a Swift library, application or test suite to be declared by build logic.

Potential implementation:

- Add binaries and tasks for each declared target operating system, similar to linkage, allowing for specific configuration per target OS.
- Fail when attempting to build on an operating system that is not supported.
- Fail when a dependency is not available on the host operating system, for all kinds of dependencies (external, source, composite, project, swift lib vs c++ lib).
- Assemble task builds the development binary for the host operating system.
- Unit test suite plugins continue to test only the development binary.
- Xcode plugin imports only the binaries for macOS operating system.

**Comment by big-guy** [comment] 2018-02-28 20:12
Dupe of #462 #463

**Closed by big-guy** 2018-02-28 20:12 UTC
