### ISSUE TITLE
Public API to allow plugins to define outgoing artifacts using the outputs of lazy tasks

### ISSUE THREAD

**Issue by ghale** [gradle/gradle-native#723] opened 2018-06-01 19:38 UTC
This should check that the task has exactly one output file and should defer resolution until `PublishArtifact.getFile()` is called.  This should work for tasks other than AbstractArchiveTask

**Comment by big-guy** [comment] 2018-08-20 20:50
maybe the same as #760

**Comment by big-guy** [comment] 2018-08-20 20:50
@ghale take a look to see if this can be closed.

**Comment by big-guy** [comment] 2018-10-29 18:10
dupe of #760

**Closed by big-guy** 2018-10-29 18:10 UTC
