### ISSUE TITLE
Native compile task should not ignore previous incremental result after build failure

### ISSUE THREAD

**Issue by lacasseio** [gradle/gradle-native#320] opened 2017-11-30 07:43 UTC
This issue was originally reported here: https://github.com/gradle/gradle/issues/3094

When using clang as the compiler, if any file fails to compile, Gradle will recompile all .o files next build

This only occurs with clang because, unlike GCC, clang will delete the output .o file if compilation fails.

Deleting the .o file causes gradle to consider all input files out-of-date and rebuild everything.
` Output property 'objectFileDirectory' file /home/dtay/src/sample-cpp/build/objs/main/mainCpp/d5jai1rac7tsmfw12u604esuq/file2.o has been removed.
All input files are considered out-of-date for incremental task ':compileMainExecutableMainCpp'.
`

### Expected Behavior
Making changes to a single .cpp file should cause recompilation of only that single .o file, even after a compilation error and using clang.

### Context
This is causing Gradle to unnecessarily rebuild far more of the project than necessary, and it occurs frequently during development.  It largely breaks the incremental build mechanism if you are using clang instead of GCC.

### Steps to Reproduce (for bugs)

See attached archive, which builds a simple 2-file cpp executable via clang using gradle.

[sample-cpp.tar.gz](https://github.com/gradle/gradle/files/1361036/sample-cpp.tar.gz)

1) Build it (./gradlew assemble)
2) Add a compilation error to one of the .cpp files
3) Rebuild, which should fail due to your new error (use --info and note that it only attempts to rebuild the modified file, as expected)
4) Fix your compilation error
5) Rebuild again (use --info; note that both of the .cpp files are rebuilt, even though one was never touched)

You can also repeat the whole thing with GCC instead of clang to see that it does not exhibit this issue because it does not delete the output .o file on a compilation failure.

**Comment by BigPapa314** [comment] 2018-12-15 08:13
This behavior may also be reproduced using GCC. Here the failing build task causes unnecessary rebuilds of source files.

### Steps to Reproduce
1. Create a project with some source files all including the same header file. 
2. Place a compile error in one of the source files.
3. Make a trivial change to the header file causing all source files to rebuild.
4. Rebuild
5. Fix the error in the source file
6. Rebuild (all source files are rebuilt even though only one has been touched)

### Expected Behavior
All source files should be compiled. One of them fails because of the local error. This causes the build task to fail. Fixing the local error and rebuilding should only rebuild the not successful built source file.

### Noticed Behavior with Gradle 5.0
`> Task :compileMainExecutableMainCpp`
`Found all include files for ':compileMainExecutableMainCpp'`
`Task ':compileMainExecutableMainCpp' is not up-to-date because:`
`    Task has failed previously.`
`All input files are considered out-of-date for incremental task ':compileMainExecutableMainCpp'.`

After that all source files are compiled again. Sadly this is a normal case in developing slightly larger c++ projects where some configuration headers are causing many source files to rebuild and a change might break one of them. The developer experience suffers heavily if one bad source file causes all other source files to rebuild until it stops causing the build task to fail.

### Possible Solutions
- Put all source files in separate build tasks so the up-to-date data is saved after a successful build
- Save the up-to-date data for every object file after its successful build (not after the build task has executed successfully)
- Cache every successful built object file immediately to speed up a not necessary rebuild of all source files

**Comment by oehme** [comment] 2021-05-16 08:39
Duplicate of https://github.com/gradle/gradle/issues/13766

**Closed** 2024-11-29 09:51 UTC
Labels: a:bug, in:language-cpp
