### ISSUE TITLE
Compilation of Swift project should not fail when project depends on a library with more than one source file and an implementation dependency on another library

### ISSUE THREAD

**Issue by adammurdoch** [gradle/gradle-native#66] opened 2017-07-28 02:01 UTC
To reproduce:

- Create a build with 3 projects app -> lib1 -> lib2.
- Use an implementation dependency from lib1 -> lib2.
- Use a single source file per project
- `gradle :app:assemble` succeeds.
- Add another source file to lib1
- `gradle :app:assemble` fails. The compile of `:app` fails, complaining that lib2 is not available (which it shouldn't be as it's an implementation dependency of lib1).

**Comment by big-guy** [comment] 2017-11-20 05:05
I couldn't reproduce this problem.

We have this test which has a similar project structure (app -> hello -> log): 
https://github.com/gradle/gradle/blob/83a6a555104746ceaa27e7c21edce5e2a9261d60/subprojects/language-native/src/integTest/groovy/org/gradle/language/swift/SwiftExecutableIntegrationTest.groovy#L354

Adding a second source file to `hello` doesn't break the build.

I think what may have been going on is #267. Maybe the first file that was added to `lib1` didn't use anything from `lib2`, but the second file did.  Since we can't separate api/implementation dependencies, this broke the `app` build.

I can reproduce that behavior by changing the test above to use `implementation` instead of `api` dependencies.

**Comment by eljobe** [comment] 2017-11-20 19:57
So, @big-guy, should we just close this as not reproducible?

**Comment by big-guy** [comment] 2017-11-20 19:58
Yes, I was going to bring it up at standup

**Closed** 2017-11-20 22:25 UTC
Labels: a:bug
