### ISSUE TITLE
Initial user guide content for the new C++ plugins

### ISSUE THREAD

**Issue by adammurdoch** [gradle/gradle-native#802] opened 2018-08-06 02:34 UTC
Add some initial user guide content for the C++ plugins. The content doesn't necessarily need to be complete or very detailed, just enough to give people some idea of the basic usage and how to solve some common use cases.

**Comment by pioterj** [comment] 2018-08-22 08:40
The new plugins should also be listed on https://docs.gradle.org/current/userguide/standard_plugins.html.

**Comment by big-guy** [comment] 2018-10-29 21:12
dupe of #677

**Closed by big-guy** 2018-10-29 21:12 UTC
