### ISSUE TITLE
configuration name clash

### ISSUE THREAD

**Issue by dhakehurst** [gradle/gradle-native#352] opened 2017-12-15 12:39 UTC
using

apply plugin: 'cpp-library'

I get error,

Cannot add a configuration with name 'implementation' as a configuration with that name already exists.

I guess it is because I am also using

apply plugin: 'java'

I want to build both java and cpp parts together, not separate.

**Comment by big-guy** [comment] 2017-12-15 16:10
Hi @dhakehurst,

Which version of Gradle are you using?

It's still an open question with how we're going to support mixing different languages into a single project.

**Comment by liblit** [comment] 2019-02-08 04:59
Still fails under Gradle 5.2. The following minimal `build.gradle` demonstrates the bug:

``` groovy
plugins {
	id 'java'
	id 'cpp-library'
}
```

Running `gradle` with no additional arguments fails:

```
FAILURE: Build failed with an exception.

* Where:
Build file '[...]/build.gradle' line: 3

* What went wrong:
An exception occurred applying plugin request [id: 'cpp-library']
> Failed to apply plugin [id 'org.gradle.cpp-library']
   > Could not create an instance of type org.gradle.language.cpp.internal.DefaultCppLibrary.
      > Could not create an instance of type org.gradle.language.internal.DefaultLibraryDependencies.
         > Cannot add a configuration with name 'implementation' as a configuration with that name already exists.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
```

The problem goes away if the plugin order is reversed so that `id 'java'` comes after `id 'cpp-library'` instead of before. This suggests that the `java` plugin may know something about avoiding configuration-name clashes that the `cpp-library` plugin does not.

**Comment by liblit** [comment] 2019-02-08 05:10
The `cpp-application` and `cpp-library` plugins are not even compatible with each other. The following `build.gradle` fails in the same manner described above regardless of which plugin is loaded first and which is loaded second:

``` groovy
plugins {
	id 'cpp-application'
	id 'cpp-library'
}
```

**Comment by melix** [comment] 2019-02-08 08:19
It's _somehow_ expected, even if the error message is not clear about this. The intention now is that a single project maps to a single component. By applying both the `java-library` and `cpp-library` plugin in a single project, you're defining 2 components in a single project. Because they share some configuration names, you get those errors.

Is there any particular reason you want to "build both java and cpp parts together, not separate", except for "they belong to the same logical thing", like, they are shipped together as a thing?

**Comment by liblit** [comment] 2019-02-08 16:35
@melix wrote:
> The intention now is that a single project maps to a single component.

Aah. If the `cpp-*` plugins are being developed with that intention locked in as mandatory policy, then that does indeed explain this failure. It also explains another problem I am seeing (but have not yet reported): my C++ builds try to find things listed as Java dependencies.

Has this one-component-per-project intention been written down anywhere that a Gradle user (but non-Gradle-developer) would see it? I always read the [Gradle Release Notes](https://docs.gradle.org/current/release-notes.html) thoroughly, and of course have read the [Gradle User Manual](https://docs.gradle.org/current/userguide/userguide.html) in detail. I peek at the [Gradle Forums](https://discuss.gradle.org/) from time to time, but don’t keep up on them religiously. I am not on any Gradle-related mailing list. Should I have known that one project is intended to build one component? Where could I have read that?

I maintain the build system for [a fairly complex project](https://github.com/wala/WALA) with over 1600 lines of Gradle build logic. If there is some documentation source that I have missed that would have told me about a one-component-per-project, then clearly I need to add that to my reading list.

> Is there any particular reason you want to "build both java and cpp parts together, not separate", except for "they belong to the same logical thing", like, they are shipped together as a thing?

I can’t speak for the other subscribers to this issue, but for me there are several reasons to build the Java and C++ components in one subproject:

1. My C++ component provides implementations of `native` methods from the Java component. Thus, the two components are _very_ tightly bound together. The two would always be shipped together. Other code would never depend on one without also requiring the other.

1. My C++ component also implements a convenient C++ wrapper for calling up into certain methods from the Java component. This is JNI in reverse: using Java to implement code that C++ applications use. So again, this leads to tight interdependence between the two components. The two would always be shipped together. Other code would never depend on one without also requiring the other.

1. Historically, the overall project was an agglomeration of many Maven subprojects. One of those Maven subprojects built both the Java and C++ components for its piece of the larger system. I replicated that structure when I created our Gradle build system. That worked with the older `cpp` plugins, but apparently is no longer supported by the newer `cpp-{application,library}` plugins.

I hope that none of these reasons are insurmountable. Until now, I had no reason to consider changing them, because I had no idea that a two-component Gradle subproject is unsupported. Now that I am aware of this restriction, I can look into pulling the Java and C++ components apart. We’ll see how it goes!

**Comment by big-guy** [comment] 2019-02-08 18:16
@liblit Nothing really written down. That's just how other plugins worked. The other `cpp` plugin was special in that it tried to break the one component == one project convention.  You were able to mix the `java` and `cpp` plugins because the `cpp` plugin didn't support much in the way of dependency management.

You don't necessarily need to change anything about how your project is structured.  You could choose to make the Java project the "primary" project and the C++ parts could be another project that's configured to look for its sources in the Java project's directory.

**Comment by lacasseio** [comment] 2019-02-11 17:34
As part of the native effort, we are moving into a more use case focused driven development which will support multiple components per project but only when required to solve the use case. In this context, JNI use case hasn't been addressed yet. It may take the form of a focused DSL that exposes both native and Java properties or something else. The basic building blocs `java`, `cpp-library` and `cpp-application` can only be used as standalone projects within a multi-project build. It is possible to create JNI project with the current building blocs but it requires a bit of configuration. We are [hoping to provide a sample](https://github.com/gradle/gradle-native/issues/208) to show how this can be done in the future. Splitting your project as Sterling mentioned is the way to go at the moment.

**Comment by liblit** [comment] 2019-02-12 02:46
@lacasseio wrote:
> Splitting your project as Sterling mentioned is the way to go at the moment.

I ended up [doing exactly that](https://github.com/wala/WALA/commit/6b5738c6dac9f30529752332461eb81908b291f2). It took quite a lot of trial and error, and likely could be done more elegantly by someone with more experience. But it works for now. I look forward to simplifying things in the future if a JNI DSL becomes available.

**Comment by liblit** [comment] 2019-02-14 05:43
It seems this is a near-duplicate of #216. The core issue is the same. However,
* #216 refers to `cpp-executable` while #352 refers to `cpp-application`, and
* #352 broadens the scope of conflicting plugins to include `java`, which #216 does not mention.

**Comment by lacasseio** [comment] 2019-02-19 00:22
@liblit `cpp-executable` was the old name for `cpp-application`. I fixed up the linked issue and broaden the scope to include `java` plugin.

Closing as duplicate.

**Closed by lacasseio** 2019-02-19 00:22 UTC

**Comment by sergeykad** [comment] 2021-07-12 14:40
> As part of the native effort, we are moving into a more use case focused driven development which will support multiple components per project but only when required to solve the use case. In this context, JNI use case hasn't been addressed yet. 

@lacasseio Are there plans to address the JNI use case?
