### ISSUE TITLE
Investigate why visual studio tests in "quick feedback" CI stage are so slow

### ISSUE THREAD

**Issue by adammurdoch** [gradle/gradle-native#703] opened 2018-05-23 21:05 UTC
The Visual studio tests are now the slowest build in the quick feedback CI state. One test in particular takes 13 minutes. Several other tests take 4 minutes. This has a large impact on dev feedback time.

We should take a look and understand why these tests are so slow, and fix if possible.

**Comment by big-guy** [comment] 2018-05-30 22:52
dupe of #613

**Closed** 2018-05-30 22:52 UTC
